name: Test Configure AWS Credential
on:
  push:
    branches:
      - main  # Triggers the pipeline when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Runs Terraform Plan for pull requests
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  cawsc:
    runs-on: ubuntu-latest

    steps:
      - name: CAWSC
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
      - name: Whoami
        run: |
          aws sts get-caller-identity
